package com.delhivery.ewaybill.common.enums;

import java.util.HashMap;
import java.util.Map;

public enum ErrorCode {
    INVALID_JSON(100, "Invalid Json"),
    INVALID_USERNAME(101, "Invalid Username"),
    INVALID_PASSWORD(102, "Invalid Password"),
    INVALID_CLIENT_ID(103, "Invalid Client -Id"),
    INVALID_CLIENT_ID_DUPLICATE(104, "Invalid Client -Id"),
    INVALID_TOKEN(105, "Invalid Token"),
    TOKEN_EXPIRED(106, "Token Expired"),
    AUTHENTICATION_FAILED(107, "Authentication failed. Pls. inform the helpdesk"),
    INVALID_LOGIN_CREDENTIALS(108, "Invalid login credentials."),
    DECRYPTION_FAILED(109, "Decryption of data failed"),
    INVALID_CLIENT_ID_SECRET(110, "Invalid Client-ID/Client-Secret"),
    GSTIN_NOT_REGISTERED(111, "GSTIN is not registerd to this GSP"),
    IMEI_NOT_BELONG_TO_USER(112, "IMEI does not belong to the user"),
    OS_TYPE_MANDATORY(113, "os-type is mandatory in header"),
    INVALID_OS_TYPE(114, "Invalid os-type parameter value"),
    INVALID_SUPPLY_TYPE(201, "Invalid Supply Type"),
    INVALID_SUB_SUPPLY_TYPE(202, "Invalid Sub-supply Type"),
    INVALID_SUB_TRANSACTION_TYPE(203, "Sub-transaction type does not belongs to transaction type"),
    INVALID_DOCUMENT_TYPE(204, "Invalid Document type"),
    DOCUMENT_TYPE_MISMATCH(205, "Document type does not match with transaction & Sub trans type"),
    INVALID_INVOICE_NUMBER(206, "Invaild Invoice Number"),
    INVALID_INVOICE_DATE(207, "Invalid Invoice Date"),
    INVALID_SUPPLIER_GSTIN(208, "Invalid Supplier GSTIN"),
    BLANK_SUPPLIER_ADDRESS(209, "Blank Supplier Address"),
    INVALID_SUPPLIER_PIN_CODE(210, "Invalid or Blank Supplier PIN Code"),
    INVALID_SUPPLIER_STATE_CODE(211, "Invalid or Blank Supplier state Code"),
    INVALID_CONSIGNEE_GSTIN(212, "Invalid Consignee GSTIN"),
    INVALID_CONSIGNEE_ADDRESS(213, "Invalid Consignee Address"),
    INVALID_CONSIGNEE_PIN_CODE(214, "Invalid Consignee PIN Code"),
    INVALID_CONSIGNEE_STATE_CODE(215, "Invalid Consignee State Code"),
    INVALID_HSN_CODE(216, "Invalid HSN Code"),
    INVALID_UQC_CODE(217, "Invalid UQC Code"),
    INVALID_TAX_RATE_INTRA_STATE(218, "Invalid Tax Rate for Intra State Transaction"),
    INVALID_TAX_RATE_INTER_STATE(219, "Invalid Tax Rate for Inter State Transaction"),
    INVALID_TRANS_MODE(220, "Invalid Trans mode"),
    INVALID_APPROX_DISTANCE(221, "Invalid Approximate Distance"),
    INVALID_TRANSPORTER_ID(222, "Invalid Transporter Id"),
    INVALID_TRANSACTION_DOCUMENT_NUMBER(223, "Invalid Transaction Document Number"),
    INVALID_TRANSACTION_DATE(224, "Invalid Transaction Date"),
    INVALID_VEHICLE_NUMBER_FORMAT(225, "Invalid Vehicle Number Format"),
    BOTH_TRANSACTION_AND_VEHICLE_NUMBER_BLANK(226, "Both Transaction and Vehicle Number Blank"),
    USER_GSTIN_CANNOT_BE_BLANK(227, "User Gstin cannot be blank"),
    USER_ID_CANNOT_BE_BLANK(228, "User id cannot be blank"),
    SUPPLIER_NAME_REQUIRED(229, "Supplier name is required"),
    SUPPLIER_PLACE_REQUIRED(230, "Supplier place is required"),
    CONSIGNEE_NAME_REQUIRED(231, "Consignee name is required"),
    CONSIGNEE_PLACE_REQUIRED(232, "Consignee place is required"),
    EWAY_BILL_NO_ITEMS(233, "Eway bill does not contains any items"),
    TOTAL_AMOUNT_TAXABLE_MANDATORY(234, "Total amount/Taxable amout is mandatory"),
    TAX_RATES_INTRA_STATE_BLANK(235, "Tax rates for Intra state transaction is blank"),
    TAX_RATES_INTER_STATE_BLANK(236, "Tax rates for Inter state transaction is blank"),
    INVALID_CLIENT_ID_SECRET_REPEATED(237, "Invalid client -Id/client-secret"),
    INVALID_AUTH_TOKEN(238, "Invalid auth token"),
    INVALID_ACTION(239, "Invalid action"),
    COULD_NOT_GENERATE_EWAY_BILL(240, "Could not generate eway bill, pls contact helpdesk"),
    INVALID_OFFICER_STATE_CODE(242, "Invalid or Blank Officer StateCode"),
    INVALID_IR_NUMBER(243, "Invalid or Blank IR Number"),
    INVALID_ACTUAL_VEHICLE_NUMBER_FORMAT(244, "Invalid or Blank Actual Vehicle Number Format"),
    INVALID_VERIFICATION_DATE_FORMAT(245, "Invalid Verification Date Format"),
    INVALID_VEHICLE_RELEASE_DATE_FORMAT(246, "Invalid Vehicle Release Date Format"),
    INVALID_VERIFICATION_TIME_FORMAT(247, "Invalid Verification Time Format"),
    ACTUAL_VALUE_LESS_THAN_ZERO(249, "Actual Value cannot be less than or equal to zero"),
    CGST_SGST_TAX_RATE_SAME(251, "CGST nad SGST TaxRate should be same"),
    INVALID_CGST_TAX_RATE(252, "Invalid CGST Tax Rate"),
    INVALID_SGST_TAX_RATE(253, "Invalid SGST Tax Rate"),
    INVALID_IGST_TAX_RATE(254, "Invalid IGST Tax Rate"),
    INVALID_CESS_RATE(255, "Invalid CESS Rate"),
    INVALID_CESS_NON_ADVOL_VALUE(256, "Invalid Cess Non Advol value"),
    USER_GSTIN_NOT_MATCH_TRANSPORTER_ID(278, "User Gstin does not match with Transporter Id"),
    STATUS_NOT_ACTIVE(280, "Status is not ACTIVE"),
    EWAY_BILL_EXPIRED(281, "Eway Bill is already expired hence update transporter is not allowed."),
    HSN_CODE_MANDATORY(282, "Atleast 4 digits HSN code is mandatory for taxpayers with turnover less than 5cr."),
    HSN_CODE_SIX_DIGITS(283, "Atleast 6 digits HSN code is mandatory for taxpayers with turnover less than 5cr. and above."),
    INVALID_EWAY_BILL_NUMBER(301, "Invalid eway bill number"),
    INVALID_TRANSPORTER_MODE(302, "Invalid transporter mode"),
    VEHICLE_NUMBER_REQUIRED(303, "Vehicle number is required"),
    INVALID_VEHICLE_FORMAT(304, "Invalid vehicle format"),
    PLACE_FROM_REQUIRED(305, "Place from is required"),
    INVALID_FROM_STATE(306, "Invalid from state"),
    INVALID_REASON(307, "Invalid reason"),
    INVALID_REMARKS(308, "Invalid remarks"),
    COULD_NOT_UPDATE_VEHICLE_DETAILS(309, "Could not update vehicle details, pl contact helpdesk"),
    VALIDITY_PERIOD_LAPSED_CANNOT_UPDATE_VEHICLE(311, "Validity period lapsed, you cannot update vehicle details"),
    EWAY_BILL_NOT_GENERATED_BY_YOU(312, "This eway bill is either not generated by you or cancelled"),
    ERROR_VALIDATING_EWAYBILL(313, "Error in validating ewaybill for vehicle updation"),
    VALIDITY_PERIOD_LAPSED_CANNOT_CANCEL(315, "Validity period lapsed, you cannot cancel this eway bill"),
    EWAY_BILL_ALREADY_VERIFIED(316, "Eway bill is already verified, you cannot cancel it"),
    COULD_NOT_CANCEL_EWAY_BILL(317, "Could not cancel eway bill, please contact helpdesk"),
    INVALID_STATE_TO(320, "Invalid state to"),
    INVALID_PLACE_TO(321, "Invalid place to"),
    COULD_NOT_GENERATE_CONSOLIDATED_EWAY_BILL(322, "Could not generate consolidated eway bill"),
    COULD_NOT_RETRIEVE_DATA(325, "Could not retrieve data"),
    COULD_NOT_RETRIEVE_GSTIN_DETAILS(326, "Could not retrieve GSTIN details for the given GSTIN number"),
    COULD_NOT_RETRIEVE_HSN_DATA(327, "Could not retrieve data from hsn"),
    COULD_NOT_RETRIEVE_TRANSPORTER_DETAILS(328, "Could not retrieve transporter details from gstin"),
    COULD_NOT_RETRIEVE_STATES_LIST(329, "Could not retrieve States List"),
    COULD_NOT_RETRIEVE_UQC_LIST(330, "Could not retrieve UQC list"),
    COULD_NOT_RETRIEVE_ERROR_CODE(331, "Could not retrieve Error code"),
    COULD_NOT_RETRIEVE_USER_DETAILS(334, "Could not retrieve user details by userid"),
    COULD_NOT_RETRIEVE_TRANSPORTER_DATA(336, "Could not retrieve transporter data by gstin"),
    COULD_NOT_RETRIEVE_HSN_DETAILS(337, "Could not retrieve HSN details for the given HSN number"),
    CANNOT_UPDATE_TRANSPORTER_DETAILS(338, "You cannot update transporter details, as the current tranporter is already entered Part B details of the eway bill"),
    NOT_ASSIGNED_UPDATE_TRANSPORTER(339, "You are not assigned to update the tranporter details of this eway bill"),
    EWAY_BILL_GENERATED_YOU_CANNOT_REJECT(341, "This e-way bill is generated by you and hence you cannot reject it"),
    CANNOT_REJECT_EWAY_BILL(342, "You cannot reject this e-way bill as you are not the other party to do so"),
    EWAY_BILL_CANCELLED(343, "This e-way bill is cancelled"),
    INVALID_EWAY_BILL_NUMBER_REPEAT(344, "Invalid eway bill number"),
    VALIDITY_PERIOD_LAPSED_CANNOT_REJECT(345, "Validity period lapsed, you cannot reject the e-way bill"),
    INVALID_EWAYBILL_ACTION(346, "You can reject the e-way bill only within 72 hours from generated timel"),
    VALIDATION_FAILED_WHILE_REJECTING(347, "Validation of eway bill number failed, while rejecting ewaybill"),
    PART_B_NOT_GENERATED(348, "Part-B is not generated for this e-way bill, hence rejection is not allowed."),
    COULD_NOT_GENERATE_CONSOLIDATED_EWAY_BILL_REPEAT(350, "Could not generate consolidated eway bill"),
    INVALID_STATE_CODE(351, "Invalid state code"),
    INVALID_RFID_DATE(352, "Invalid rfid date"),
    INVALID_LOCATION_CODE(353, "Invalid location code"),
    INVALID_RFID_NUMBER(354, "Invalid rfid number"),
    INVALID_VEHICLE_NUMBER_FORMAT_REPEAT(355, "Invalid Vehicle Number Format"),
    INVALID_WT_ON_BRIDGE(356, "Invalid wt on bridge"),
    COULD_NOT_RETRIEVE_EWAY_BILL_DETAILS(357, "Could not retrieve eway bill details, pl. contact helpdesk"),
    GSTIN_NOT_MATCHING_USER_GSTIN(358, "GSTIN passed in request header is not matching with the user gstin mentioned in payload JSON"),
    USER_GSTIN_SHOULD_MATCH_GSTIN_FROM(359, "User GSTIN should match to GSTIN(from) for outward transactions"),
    USER_GSTIN_SHOULD_MATCH_GSTIN_TO(360, "User GSTIN should match to GSTIN(to) for inward transactions"),
    INVALID_VEHICLE_TYPE(361, "Invalid Vehicle Type"),
    TRANSPORTER_DOC_DATE_EARLIER_THAN_INVOICE(362, "Transporter document date cannot be earlier than the invoice date"),
    EWAY_BILL_NOT_ENABLED_FOR_INTRA_STATE(363, "E-way bill is not enabled for intra state movement for you state"),
    ERROR_VERIFYING_EWAY_BILL(364, "Error in verifying eway bill"),
    ERROR_VERIFYING_CONSOLIDATED_EWAY_BILL(365, "Error in verifying consolidated eway bill"),
    EWAYBILLS_NOT_AVAILABLE_TODAY(366, "You will not get the ewaybills generated today, howerver you cann access the ewaybills of yester days"),
    COULD_NOT_RETRIEVE_DATA_OFFICER_LOGIN(367, "Could not retrieve data for officer login"),
    COULD_NOT_UPDATE_TRANSPORTER(368, "Could not update transporter"),
    GSTIN_TRANSIN_NOT_MATCHING_TRANSPORTER_ID(369, "GSTIN/Transin passed in request header should match with the transported Id mentioned in payload JSON"),
    GSTIN_TRANSIN_NOT_SAME_AS_SUPPLIER_OR_RECEPIENT(370, "GSTIN/Transin passed in request header should not be the same as supplier(fromGSTIN) or recepient(toGSTIN)"),
    INVALID_SUPPLIER_SHIP_TO_STATE_CODE(371, "Invalid or Blank Supplier Ship-to State Code"),
    INVALID_CONSIGNEE_SHIP_TO_STATE_CODE(372, "Invalid or Blank Consignee Ship-to State Code"),
    SUPPLIER_SHIP_TO_STATE_CODE_OTHER_COUNTRY(373, "The Supplier ship-to state code should be Other Country for Sub Supply Type- Export"),
    CONSIGNEE_PIN_CODE_999999(374, "The Consignee pin code should be 999999 for Sub Supply Type- Export"),
    SUPPLIER_SHIP_FROM_STATE_CODE_OTHER_COUNTRY(375, "The Supplier ship-from state code should be Other Country for Sub Supply Type- Import"),
    SUPPLIER_PIN_CODE_999999(376, "The Supplier pin code should be 999999 for Sub Supply Type- Import"),
    SUB_SUPPLY_TYPE_OTHERS_DESCRIPTION_MANDATORY(377, "Sub Supply Type is mentioned as Others, the description for that is mandatory"),
    SEZ_INTER_STATE_TAX_RATES_APPLICABLE(378, "The supplier or conginee belong to SEZ, Inter state tax rates are applicable here"),
    EWAY_BILL_CANNOT_BE_EXTENDED_ALREADY_CANCELLED(379, "Eway Bill can not be extended.. Already Cancelled"),
    EWAY_BILL_CANNOT_BE_EXTENDED_NOT_ACTIVE(380, "Eway Bill Can not be Extended. Not in Active State"),
    NO_PART_B_VEHICLE_ENTRY(381, "There is No PART-B/Vehicle Entry.. So Please Update Vehicle Information.."),
    CANNOT_EXTEND_EWB_BEFORE_OR_AFTER_VALIDITY(382, "You Cannot Extend as EWB can be Extended only 8 hour before or after w.r.t Validity of EWB..!!"),
    ERROR_EXTENDING_EWB(383, "Error While Extending..Please Contact Helpdesk."),
    NOT_CURRENT_TRANSPORTER_OR_GENERATOR(384, "You are not current transporter or Generator of the ewayBill, with no transporter details."),
    TRANS_DOC_DATE_MANDATORY_FOR_RAIL_SHIP_AIR(385, "For Rail/Ship/Air transDocDate is mandatory"),
    REASON_CODE_REMARKS_MANDATORY(386, "Reason Code, Remarks is mandatory."),
    NO_RECORD_FOUND_FOR_CONSOLIDATED_EWAY_BILL(387, "No Record Found for Entered consolidated eWay bill."),
    EXCEPTION_REGENERATING_CONSOLIDATED_EWAY_BILL(388, "Exception in regenration of consolidated eWayBill!!Please Contact helpdesk"),
    REMAINING_DISTANCE_REQUIRED(389, "Remaining Distance Required"),
    REMAINING_DISTANCE_GREATER_THAN_ACTUAL(390, "Remaining Distance Can not be greater than Actual Distance."),
    NO_EWAY_BILL_SPECIFIED_TRIPSHEET(391, "No eway bill of specified tripsheet, neither ACTIVE nor not Valid."),
    TRIPSHEET_ALREADY_CANCELLED(392, "Tripsheet is already cancelled, Hence Regeration is not possible"),
    INVALID_GSTIN(393, "Invalid GSTIN"),
    TRANS_DOC_NUMBER_REQUIRED_FOR_NON_ROAD(394, "For other than Road Transport, TransDoc number is required"),
    EWAY_BILL_NUMBER_NUMERIC_ONLY(395, "Eway Bill Number should be numeric only"),
    EWAY_BILL_OR_CONSOLIDATED_EWAY_BILL_REQUIRED(396, "Either Eway Bill Number Or Consolidated Eway Bill Number is required for Verification"),
    ERROR_MULTI_VEHICLE_MOVEMENT_INITIATION(397, "Error in Multi Vehicle Movement Initiation"),
    EWAY_BILL_ITEM_LIST_EMPTY(398, "Eway Bill Item List is Empty"),
    UNIT_CODE_NOT_MATCHING_ITEM_LIST(399, "Unit Code is not matching with any of the Unit Code from ItemList"),
    TOTAL_QUANTITY_EXCEEDING_MULTI_VEHICLE(400, "total quantity is exceeding from multi vehicle movement initiation quantity"),
    ERROR_INSERTING_MULTI_VEHICLE_DETAILS(401, "Error in inserting multi vehicle details"),
    TOTAL_QUANTITY_LESS_THAN_ZERO(402, "total quantity can not be less than or equal to zero"),
    ERROR_MULTI_VEHICLE_DETAILS(403, "Error in multi vehicle details"),
    NO_RECORD_FOUND_MULTI_VEHICLE_UPDATE(405, "No record found for multi vehicle update with specified ewbNo groupNo and old vehicleNo/transDocNo with status as ACT"),
    GROUP_NUMBER_CANNOT_BE_EMPTY(406, "Group number cannot be empty or zero"),
    INVALID_OLD_VEHICLE_NUMBER_FORMAT(407, "Invalid old vehicle number format"),
    INVALID_NEW_VEHICLE_NUMBER_FORMAT(408, "Invalid new vehicle number format"),
    INVALID_OLD_TRANS_DOC_NUMBER(409, "Invalid old transDoc number"),
    INVALID_NEW_TRANS_DOC_NUMBER(410, "Invalid new transDoc number"),
    MULTI_VEHICLE_INITIATION_DATA_NOT_FOUND(411, "Multi Vehicle Initiation data is not there for specified ewayBill and group No"),
    MULTI_VEHICLE_MOVEMENT_ALREADY_INITIATED(412, "Multi Vehicle movement is already Initiated,hence PART B updation not allowed"),
    UNIT_CODE_NOT_MATCHING_FIRST_INITIATION(413, "Unit Code is not matching with unit code of first initiaton"),
    ERROR_FETCHING_VERIFICATION_DATA_OFFICER(415, "Error in fetching in verification data for officer"),
    DATE_RANGE_EXCEEDING_ALLOWED(416, "Date range is exceeding allowed date range"),
    NO_VERIFICATION_DATA_FOUND_OFFICER(417, "No verification data found for officer"),
    NO_RECORD_FOUND(418, "No record found"),
    ERROR_FETCHING_SEARCH_RESULT(419, "Error in fetching search result for taxpayer/transporter"),
    MINIMUM_SIX_CHAR_REQUIRED_TRADE_NAME(420, "Minimum six character required for Tradename/legalname search"),
    INVALID_PINCODE(421, "Invalid pincode"),
    INVALID_MOBILE_NUMBER(422, "Invalid mobile number"),
    ERROR_FETCHING_EWAYBILL_LIST_BY_VEHICLE(423, "Error in fetching ewaybill list by vehicle number"),
    INVALID_PAN_NUMBER(424, "Invalid PAN number"),
    ERROR_FETCHING_PART_A_DATA_BY_IR_NUMBER(425, "Error in fetching Part A data by IR Number"),
    VEHICLE_RELEASE_DATE_TIME_MANDATORY(426, "For Vehicle Released vehicle release date and time is mandatory"),
    ERROR_SAVING_PART_A_VERIFICATION_REPORT(427, "Error in saving Part-A verification Report"),
    CODE_428(428, "For Goods Detained, Vehicle Released field is mandatory"),
    CODE_429(429, "Error in saving Part-B verification Report"),
    CODE_430(430, "Goods Detained Field required."),
    CODE_431(431, "Part-A for this ewaybill is already generated by you."),
    CODE_432(432, "Invalid vehicle released value"),
    CODE_433(433, "Invalid goods detained parameter value"),
    CODE_434(434, "Invalid ewbNoAvailable parameter value"),
    CODE_435(435, "Part B is already updated, hence updation is not allowed"),
    CODE_436(436, "Invalid Consignee ship to State Code for the given pincode"),
    CODE_437(437, "Invalid Supplier ship from State Code for the given pincode"),
    CODE_438(438, "Invalid Latitude"),
    CODE_439(439, "Invalid Longitude"),
    CODE_440(440, "Error in inserting in verification data"),
    CODE_441(441, "Invalid verification type"),
    CODE_442(442, "Error in inserting verification details"),
    CODE_443(443, "Invalid invoice available value"),
    CODE_600(600, "Invalid category"),
    CODE_601(601, "Invalid date format"),
    CODE_602(602, "Invalid File Number"),
    CODE_603(603, "For file details file number is required"),
    CODE_604(604, "E-way bill(s) are already generated for the same document number, you cannot generate again on same document number"),
    CODE_607(607, "Dispatch from GSTIN is mandatory"),
    CODE_608(608, "Ship to from GSTIN is mandatory"),
    CODE_609(609, "Invalid ship to from GSTIN"),
    CODE_610(610, "Invalid dispatch from GSTIN"),
    CODE_611(611, "Invalid document type for the given supply type"),
    CODE_612(612, "Invalid transaction type"),
    CODE_613(613, "Exception in getting Officer Role"),
    CODE_614(614, "Transaction type is mandatory"),
    CODE_615(615, "Dispatch From GSTIN cannot be sent as the transaction type selected is Regular"),
    CODE_616(616, "Ship to GSTIN cannot be sent as the transaction type selected is Regular"),
    CODE_617(617, "Bill-from and dispatch-from GSTIN should not be same for this transaction type"),
    CODE_618(618, "Bill-to and ship-to GSTIN should not be same for this transaction type"),
    CODE_619(619, "Transporter Id is mandatory for generation of Part A slip"),
    CODE_620(620, "Total invoice value cannot be less than the sum of total assessable value and tax values"),
    CODE_621(621, "Trans mode is mandatory since vehicle number is present"),
    CODE_622(622, "Trans mode is mandatory since trans doc number is present"),
    CODE_623(623, "IGST value is not applicable for Intra State Transaction"),
    CODE_624(624, "SGST/CGST value is not applicable for Inter State Transaction"),
    CODE_627(627, "Total value should not be negative"),
    CODE_628(628, "Total invoice value should not be negative"),
    CODE_629(629, "IGST value should not be negative"),
    CODE_630(630, "CGST value should not be negative"),
    CODE_631(631, "SGST value should not be negative"),
    CODE_632(632, "Cess value should not be negative"),
    CODE_633(633, "Cess non advol should not be negative"),
    CODE_634(634, "Vehicle type should not be ODC when transmode is other than road"),
    CODE_635(635, "You cannot update part B, as the current transporter is already entered Part B details of the eway bill"),
    CODE_636(636, "You are not assigned to update part B"),
    CODE_637(637, "You cannot extend ewaybill, as the current transporter is already entered Part B details of the ewaybill"),
    CODE_638(638, "Transport mode is mandatory as Vehicle Number/Transport Document Number is given"),
    CODE_640(640, "Total Invoice Value is mandatory"),
    CODE_641(641, "For outward CKD/SKD/Lots supply type, Bill To state should be as Other Country, since the Bill To GSTIN given is of SEZ unit"),
    CODE_642(642, "For inward CKD/SKD/Lots supply type, Bill From state should be as Other Country, since the Bill From GSTIN given is of SEZ unit"),
    CODE_643(643, "For regular transaction, Bill from state code and Dispatch from state code should be same"),
    CODE_644(644, "For regular transaction, Bill to state code and Ship to state code should be same"),
    CODE_645(645, "You cannot do Multi Vehicle movement, as current transporter already entered part B"),
    CODE_646(646, "You are not assigned to do multi vehicle movement"),
    CODE_647(647, "Could not insert RFID data, please contact helpdesk"),
    CODE_648(648, "Multi Vehicle movement is already Initiated, hence generation of consolidated eway bill is not allowed"),
    CODE_649(649, "You cannot generate consolidated eway bill, as the current transporter is already entered Part B details of the eway bill"),
    CODE_650(650, "You are not assigned to generate consolidated ewaybill"),
    CODE_651(651, "For Category Part-A or Part-B ewbdt is mandatory"),
    CODE_652(652, "For Category EWB03 procdt is mandatory"),
    CODE_654(654, "This GSTIN has generated a common Enrolment Number. Hence you are not allowed to generate Eway bill"),
    CODE_655(655, "This GSTIN has generated a common Enrolment Number. Hence you cannot mention it as a transporter"),
    CODE_656(656, "This Eway Bill does not belong to your state"),
    CODE_657(657, "Eway Bill Category wise details will be available after 4 days only"),
    CODE_658(658, "You are blocked for accessing this API as the allowed number of requests has been exceeded for this duration"),
    CODE_659(659, "Remarks is mandatory"),
    CODE_670(670, "Invalid Month Parameter"),
    CODE_671(671, "Invalid Year Parameter"),
    CODE_672(672, "User Id is mandatory"),
    CODE_673(673, "Error in getting officer dashboard"),
    CODE_675(675, "Error in getting EWB03 details by acknowledgement date range"),
    CODE_676(676, "Error in getting EWB Not Available List by entered date range"),
    CODE_677(677, "Error in getting EWB Not Available List by closed date range"),
    CODE_678(678, "Invalid Uniq No"),
    CODE_679(679, "Invalid EWB03 Ack No"),
    CODE_680(680, "Invalid Close Reason"),
    CODE_681(681, "Error in Closing EWB Verification Data"),
    CODE_682(682, "No Record available to Close"),
    CODE_683(683, "Error in fetching WatchList Data"),
    CODE_685(685, "Exception in fetching dashboard data"),
    CODE_700(700, "You are not assigned to extend e-waybill"),
    CODE_701(701, "Invalid Vehicle Direction"),
    CODE_702(702, "The distance between the pincodes given is too high"),
    CODE_703(703, "Since the consignor is Composite Taxpayer, inter state transactions are not allowed"),
    CODE_704(704, "Since the consignor is Composite Taxpayer, Tax rates should be zero"),
    CODE_705(705, "Invalid transit type"),
    CODE_706(706, "Address Line1 is mandatory"),
    CODE_707(707, "Address Line2 is mandatory"),
    CODE_708(708, "Address Line3 is mandatory"),
    CODE_709(709, "Pin to pin distance is not available for the given pin codes"),
    CODE_710(710, "Invalid state code for the given pincode"),
    CODE_711(711, "Invalid value for isInTransit field"),
    CODE_712(712, "Transit Type is not required as the goods are not in movement"),
    CODE_713(713, "Transit Address is not required as the goods are not in movement"),
    CODE_714(714, "Document type - Tax Invoice is not allowed for composite tax payer"),
    CODE_715(715, "The Consignor GSTIN is blocked from e-waybill generation as Return is not filed for past 2 months"),
    CODE_716(716, "The Consignee GSTIN is blocked from e-waybill generation as Return is not filed for past 2 months"),
    CODE_717(717, "The Transporter GSTIN is blocked from e-waybill generation as Return is not filed for past 2 months"),
    CODE_718(718, "The User GSTIN is blocked from Transporter Updation as Return is not filed for past 2 months"),
    CODE_719(719, "The Transporter GSTIN is blocked from Transporter Updation as Return is not filed for past 2 months"),
    CODE_720(720, "E Way Bill should be generated as part of IRN generation or with reference to IRN in E Invoice System, Since Supplier is enabled for E Invoice."),
    CODE_721(721, "The distance between the given pincodes are not available in the system. Please provide distance."),
    CODE_722(722, "Consignee GSTIN is cancelled and document date is later than the De-Registration date"),
    CODE_724(724, "HSN code of at least one item should be of goods to generate e-Way Bill"),
    CODE_726(726, "Vehicle type cannot be regular when transportation mode is ship"),
    CODE_727(727, "For Ship Transport, either vehicle number or transport document number is required"),
    CODE_728(728, "You can cancel the ewaybill within 24 hours from Part B entry"),
    CODE_729(729, "TransDoc date is required for transport mode Ship as the transport document number is provided"),
    CODE_813(813, "Duplicate request at the same time"),
    CODE_817(817, "MultiVehicleMovement cannot be initiated. Eway Bill is not in Active State"),
    CODE_818(818, "Validity period lapsed. Cannot generate consolidated Eway Bill"),
    CODE_819(819, "Ewaybill cannot be generated for the document date which is prior to 01/07/2017");



    private final int code;
    private final String message;

    private static final Map<Integer, String> errorMap = new HashMap<>();

    static {
        for (ErrorCode error : ErrorCode.values()) {
            errorMap.put(error.code, error.message);
        }
    }

    ErrorCode(int code, String message) {
        this.code = code;
        this.message = message;
    }

    public static String getMessageByCode(int code) {
        System.out.println("Error code: " + code);
        return errorMap.getOrDefault(code, "Unknown error code");
    }

    public int getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }
}

